# Site settings
title: Toast Lab
description: We together orchestrate architecture, system, and theory for computing.
baseurl: "" 
#change the baseurl to "" if you are using it as your user GitHub Pages
url: "https://toast-lab.github.io"  


# GitHub User settings
username: toast-lab
github_username: toast-lab
user_description: Director of Toast Lab
user_title: toast-lab
email: 

# Blog Author settings
author: 
  name: 
  picture:        
  email: 
  description: 
  twitter:
  facebook:
  github:          
  linkedin:
  clustrmap:      


# markdown
markdown: kramdown
  
kramdown:
 footnote_nr: 1
 entity_output: as_char
 # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
 syntax_highlighter: rouge
 syntax_highlighter_opts:
  # Use existing pygments syntax highlighting css
  css_class: 'highlight'
 span:
  line_numbers: false
 block:
  line_numbers: true
  start_line: 1
 
highlighter: rouge
    
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
permalink: none

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      toc: true
      mathjax: true
      mermaid: false
      highlight: false
      numbering: true
      status: Completed
      protected: false
      commentable: true
      rss: true
      numbering: true

exclude:
 - LICENSE.md
 - README.md
 - "*.cdf"
 - "*.nb"
 - "*.bk"
 - "*.draft.md"
